language: ruby
cache: bundler
rvm:
- 1.9.3-p484
- 2.0.0-p353
- 2.1.0
- 2.1.2
- 2.1.3
- 2.1.4
notifications:
  email: false
  slack:
    secure: dWunGMhRwSmsVhc/wJD0EDVH/PTLtzb1G+ZExj28gWCdZ7ojTgrFDUiAAqxli/FrtpQTUsX8K7eYjlQLPc5vmNCdUes8537r8vmPz7p6m97A5rehBsIWfgYZNKKA3hxvWAoCryOdUwbUsihSmpTmQTfRSH4SZfOmRPuRzzmrVFA=
addons:
  code_climate:
    repo_token: 9bd643c8090c8ef179d2b7d20d41d2e4399c031f621efdb125c1dc2ca5d9e6cc
